volumes:
  postgres_data:

services:
  db:
    container_name: cinema-world-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cinema-world-db
    ports:
      - "5432:5432"
  play:
    container_name: cinema-world-app
    image: dando500/cinema-world
    restart: always
    ports:
      - "9000:9000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    depends_on:
      - db

